//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.4
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo.hello.slice;

/** @hidden */
public class _PrinterPrxI extends com.zeroc.Ice._ObjectPrxI implements PrinterPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
